### ISSUE TITLE
Feature request: app: Show selected masteries

### ISSUE THREAD

**Issue by ArsileLuci** [Dav1dde/pasteofexile#6]
First of all thanks for the awesome job you've done here.

I would like to see currently selected masteries next to the tree.

Also I would like to help with implementation of this feature, and others in future. If it possible could you please, provide insight on overall architecture under [Contributing](https://github.com/Dav1dde/pasteofexile#contributing) section in README, this will be very helpful.

**Comment by Dav1dde** [comment]
Thanks for the kind words! 

It's on my todo, I want to show Keystones and allocated Masteries.

This unfortunately is not a trivial feature to implement, this requires extracting the information from either game files or the [tree JSONs](https://github.com/grindinggear/skilltree-export/) at build time.
Then we need to enrich the JSON endpoint with the data of the correct tree version for each tree (which could be from different game versions).

Regarding the Contributing section, yeah this could be improved quite a bit, but there are a few bigger refactorings on the horizon (e.g. updating sycamore to 0.8 which requires almost an entire rewrite of the 'frontend'), that's why I've been holding off and don't recommend investing too much time into a PR, because things will change quite a bit soon. Best way to contribute right now is through ideas and UI mockups.
